
resource_group_name ="rg-ecommerce-dev"
location = "westeurope"
environnement = "dev" 
storage_account_name = "mystoragebass224"
container_name = ""
datafactory_name = "my-datafact-bass-dev"
db_workspace_name = "my-wkspace-bass-dev"
sql_server_name = "my-sqlserver-bass224-new-dev"
mydb_name = "ecom-dev"
resource_group_keyvault_name ="rg_ecommerce-securite-dev"
key_vault_name ="myecommercekvdev"
role_assignement_writer="Key Vault Secrets Officer"
role_assignement_reader = "Key Vault Secrets User"
ls_kv_name = "KV_LS"
secret_name = "sql-admin-password"
ls_sql_name ="SQL_LS"