
resource_group_name ="rg-ecommerce-dev"
location = "westeurope"
environnement = "dev" 
storage_account_name = "mystoragebass224"
container_name = ""
datafactory_name = "my-datafact-bass-dev"
db_workspace_name = "my-wkspace-bass-dev"
sql_server_name = "my-sqlserver-bass-dev"
sql_database_login = ""
sql_database_password = ""