
resource_group_name ="rg-ecommerce-dev"
location = "westeurope"
environnement = "dev" 
storage_account_name = "mystoragebass224"
container_name = ""
datafactory_name = "my-datafact-bass-dev"
db_workspace_name = "my-wkspace-bass-dev"
sql_server_name = "my-sqlserver-bass224-new-dev"
mydb_name = "ecom-dev"
sql_database_ls_name = "SQL_LS"
resource_group_keyvault_name ="rg_ecommerce-securite-dev"
key_vault_name ="myecommercekvdev"